version: '3.4'
services:
  minio:
    image: quay.io/minio/minio:latest
    restart: always
    command: "server /data --console-address :9090"
    ports:
      - "127.0.0.1:9090:9090"
      - "127.0.0.1:9000:9000"
